# Generated by Django 2.2.9 on 2020-02-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('faq', '0003_auto_20200206_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='faq_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
