# Generated by Django 2.2.9 on 2020-02-16 06:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_auto_20200213_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='faqs',
            field=wagtail.core.fields.StreamField([('faqs', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('content', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('content', wagtail.core.blocks.RichTextBlock())]))]))], blank=True, null=True),
        ),
    ]
