# Generated by Django 2.2.9 on 2020-02-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0011_auto_20200216_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='faqs',
        ),
    ]
