# Generated by Django 2.2.9 on 2020-02-15 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200204_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetailpage',
            name='news_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
