# Generated by Django 2.2.9 on 2020-02-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200215_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetailpage',
            name='custom_title',
            field=models.CharField(help_text='Overwrites the default title', max_length=200),
        ),
    ]
