# Generated by Django 2.2.9 on 2020-02-04 08:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailimages', '0001_squashed_0021'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestPaperPage',
            new_name='InvestPage',
        ),
    ]
