# Generated by Django 2.2.9 on 2020-02-04 09:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0003_capitalizeverbose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('disclaimer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisclaimerPaperPage',
            new_name='DisclaimerPage',
        ),
    ]
