# Generated by Django 2.2.9 on 2020-02-04 01:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whitepaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitepaperpage',
            name='summary',
            field=wagtail.core.fields.RichTextField(default='Input here...'),
        ),
    ]
