# Generated by Django 2.2.9 on 2020-02-04 05:36

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='subtitle',
            field=wagtail.core.fields.RichTextField(default='Input here...'),
        ),
    ]
