# Generated by Django 2.2.9 on 2020-02-03 07:13

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='summary',
            field=models.CharField(default='Input the summary...', help_text='Overwrites the default title', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='content',
            field=wagtail.core.fields.RichTextField(default='Input here...'),
        ),
    ]
